db:
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  maxOpenPreparedStatements: 20
  master:
    url: jdbc:mysql://dev.360ease.com:3326/dev_lily?zeroDateTimeBehavior=convertToNull
    username: dev
    password: dev360ease
