package com.abc.demo.entity;


/**
* 
* PostBase.
* auto generated by jasmine, please do not modify it!
*/
public class PostBase {

    /**
    * 
    */
	private Long id;
    /**
    * 
    */
	private String content;
    /**
    * 
    */
	private java.util.Date createTime;
    /**
    * 
    */
	private Long userId;
    /**
    * 
    */
	private Long threadId;
    /**
    * 
    */
	private String sellerNick;
  
  	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

  	public java.util.Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(java.util.Date createTime) {
		this.createTime = createTime;
	}

  	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

  	public Long getThreadId() {
		return threadId;
	}

	public void setThreadId(Long threadId) {
		this.threadId = threadId;
	}

  	public String getSellerNick() {
		return sellerNick;
	}

	public void setSellerNick(String sellerNick) {
		this.sellerNick = sellerNick;
	}

  }