package com.abc.demo.entity;


/**
* 吐槽文章
* ThreadBase.
* auto generated by jasmine, please do not modify it!
*/
public class ThreadBase {

    /**
    * 
    */
	private Long id;
    /**
    * 内容
    */
	private String content;
    /**
    * 
    */
	private java.util.Date createTime;
    /**
    * 
    */
	private boolean readed;
    /**
    * 
    */
	private boolean replied;
    /**
    * 
    */
	private Long userId;
    /**
    * 
    */
	private String sellerNick;
  
  	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

  	public java.util.Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(java.util.Date createTime) {
		this.createTime = createTime;
	}

  	public boolean isReaded() {
		return readed;
	}

	public void setReaded(boolean readed) {
		this.readed = readed;
	}

  	public boolean isReplied() {
		return replied;
	}

	public void setReplied(boolean replied) {
		this.replied = replied;
	}

  	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

  	public String getSellerNick() {
		return sellerNick;
	}

	public void setSellerNick(String sellerNick) {
		this.sellerNick = sellerNick;
	}

  }