package com.abc.demo.repository;

import com.abc.demo.entity.Post;
import org.apache.ibatis.annotations.Param;

import java.util.Map;

/**
* PostRepositoryBase.
* auto generated by jasmine, please do not modify it!
*/
public interface PostRepositoryBase{
    /**
    * physical delete
    * @param id
    * @return
    */
    int delete(String id);

    Post get(String id);

    /**
    * insert entity
    * @param entity
    * @return
    */
    int insert(Post entity);

    /**
    * update
    * @param entity
    * @return
    */
    int update(Post entity);

    /**
    * update table set ${column} = #{value} where id = #{id}
    * @param id
    * @param column
    * @param value
    * @return
    */
    int updateColumn(@Param("id") String id, @Param("column") String column, @Param("value") Object value);

    /**
    * update table set ${column1} = #{value1}, ${column2} = #{value2}, ..., ${column-n} = #{value-n} where id = #{id}
    * @param id
    * @param columnWithValues
    * @return
    */
    int updateColumns(@Param("id") String id, @Param("columnWithValues") Map<String, Object> columnWithValues);
}
